-- INSERT INTO USER( `name` ,`surname`, `email`, `password`)
-- VALUES
-- ('Arturs', 'Uzvards', 'arturs@mail.com', 'arturs1');
--
-- INSERT INTO USER( `name` ,`surname`, `email`, `password`)
-- VALUES
-- ('Mara', 'Uzvards', 'mara@mail.com', 'mara1');
--
-- INSERT INTO USER( `name` ,`surname`, `email`, `password`)
-- VALUES
-- ('Admins', 'Uzvards', 'admin@mail.com', 'admin1');
